## ---------------------------------------------------------------------------
## WMBUS METER for Diehl IZAR RC 868 (ESP32 + CC1101)
## Generische Version für GitHub
## ---------------------------------------------------------------------------
substitutions:
  device_name_short: "water-meter-esp"
  friendly_name: "Wasserzähler"
  appversion: "3.2.0"
  
  # ZÄHLER-ID hier oder in secrets.yaml definieren
  # Format: "0x12345678"
  wmid: !secret watermeter_id

esphome:
  name: ${device_name_short}
  platformio_options:
    platform: espressif32
    board: az-delivery-devkit-v4
    build_flags:
      - "-UCONFIG_ARDUINO_LOOP_STACK_SIZE"
      - "-DCONFIG_ARDUINO_LOOP_STACK_SIZE=32768"
  on_boot:
    priority: -10
    then:
      - globals.set:
          id: boot_counter
          value: !lambda "return id(boot_counter) + 1;"

external_components:
  - source: github://SzczepanLeon/esphome-components@version_3
    refresh: 0s
    components: [ wmbus ]

logger:
  level: INFO # Für Setup auf DEBUG stellen
  baud_rate: 115200
  logs:
    wmbus: WARN

globals:
  - id: boot_counter
    type: int
    restore_value: yes
    initial_value: "0"
  - id: last_value 
    type: float
    restore_value: yes
    initial_value: "0.00"
  - id: hour_value 
    type: float
    restore_value: yes
    initial_value: "0.00"
  - id: daily_value
    type: float
    restore_value: yes
    initial_value: "0.00"
  - id: week_value
    type: float
    restore_value: yes
    initial_value: "0.00"
  - id: year_value
    type: float
    restore_value: yes
    initial_value: "0.00"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

time:
  - platform: sntp
    id: time_sntp
    timezone: Europe/Berlin
    on_time:
      - seconds: 0
        minutes: 0
        then:
          - lambda: |-
              id(hour_value) = 0.0;
              id(waterhour).publish_state(0);
      - seconds: 0
        minutes: 0
        hours: 0
        then:
          - lambda: |-
              id(daily_value) = 0.0;
              id(waterday).publish_state(0);

api:
  reboot_timeout: 0s
  services:
    - service: set_stats
      variables:
        h: float
        d: float
      then:
        - lambda: |-
            id(hour_value) = h;
            id(daily_value) = d;
            id(waterhour).publish_state(h);
            id(waterday).publish_state(d);

ota:
  - platform: esphome
    password: !secret ota_password

web_server:
  port: 80

wmbus:
  mosi_pin: GPIO23
  miso_pin: GPIO19
  clk_pin: GPIO18
  cs_pin: GPIO5 
  gdo0_pin: GPIO16
  gdo2_pin: GPIO17
  log_unknown: False

sensor:
  - platform: wmbus
    meter_id: ${wmid}
    type: izar
    add_prefix: false
    
    lqi:
      name: "${friendly_name} LQI"
      accuracy_decimals: 0
    rssi:
      name: "${friendly_name} RSSI"
      accuracy_decimals: 0
      filters:
        - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
      unit_of_measurement: "%"

    total_water_m3:
      id: "waterdisplay"
      name: "${friendly_name} Zählerstand"
      unit_of_measurement: "m³"
      accuracy_decimals: 3
      device_class: "water"
      state_class: total_increasing
      on_value:
        then:
          - lambda: |-
              float current_m3 = x;
              if (id(last_value) <= 0.01) {
                id(last_value) = current_m3;
                ESP_LOGI("custom", "Baseline gesetzt: %.3f m³.", current_m3);
                return;
              }
              if (current_m3 > id(last_value)) {
                float liters = (current_m3 - id(last_value)) * 1000.0;
                id(hour_value) += liters;
                id(daily_value) += liters;
                id(week_value) += liters;
                id(year_value) += liters;
                
                id(waterhour).publish_state(id(hour_value));
                id(waterday).publish_state(id(daily_value));
                id(waterweek).publish_state(id(week_value));
                id(wateryear).publish_state(id(year_value));
                
                id(last_value) = current_m3;
                ESP_LOGI("custom", "Verbrauch: %.2f L (Gesamt: %.3f m³)", liters, current_m3);
              }

    remaining_battery_life_y:
      name: "${friendly_name} Batterie"
    transmit_period_s:
      name: "${friendly_name} Sendeintervall"

  - platform: template
    name: "${friendly_name} Stunde"
    id: "waterhour"
    unit_of_measurement: "L"
    device_class: "water"
    state_class: total_increasing
    accuracy_decimals: 2
  - platform: template
    name: "${friendly_name} Tag"
    id: "waterday"
    unit_of_measurement: "L"
    device_class: "water"
    state_class: total_increasing
    accuracy_decimals: 2
  - platform: template
    name: "${friendly_name} Woche"
    id: "waterweek"
    unit_of_measurement: "L"
    device_class: "water"
    state_class: total_increasing
    accuracy_decimals: 2
  - platform: template
    name: "${friendly_name} Jahr"
    id: "wateryear"
    unit_of_measurement: "L"
    device_class: "water"
    state_class: total_increasing
    accuracy_decimals: 2

  - platform: uptime
    name: "${friendly_name} Uptime"
    unit_of_measurement: "h"
    accuracy_decimals: 2
    filters:
      - lambda: return x / 3600.0;

  - platform: internal_temperature
    name: "${friendly_name} ESP32 Temperatur"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer-chip"
